[package]
name = "foxdie"
version = "0.5.0"
authors = ["Aaron Sky <asky@wayfair.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
chrono = "0.4"
env_logger = "0.6"
log = "0.4"
foxdie_actions = { version = "0.5.0", path = "../foxdie_actions" }
