name: CI
on: push
jobs:
  main:
    steps:
      - name: Workspace Info
        run: |
          uname -a
          ls
      - name: Lint
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy -- -Dwarnings
      - name: Test
        run: cargo test
    runs-on: ubuntu-latest