name: CI

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - run: cargo fmt -- --check
      - run: cargo clippy -- -Dwarnings
      - run: cargo test
